### ISSUE TITLE
Could you please enable SVG support?

### ISSUE THREAD

**Issue by bazizi** [ewpratten/raylib-ffi#12]
SVG support can be enabled by setting the `SUPPORT_FILEFORMAT_SVG` macro. Can you please make it a rust feature that we can enable, or just enable it by default?

Thanks!

**Comment by ewpratten** [comment]
`v5.0.2` published. It _should_ do what you want. If not, please let me know.

**Comment by bazizi** [comment]
Unfortunately, this didn't work as the `third_party\raylib\src\rtextures.ch` source file needs to be compiled with the `SUPPORT_FILEFORMAT_SVG` (the macro needs to be passed to the compiler). 

I managed to resolve the issue locally in a hacky way, that is, by adding the macro to `raylib.h` itself:

```cpp
#define SUPPORT_FILEFORMAT_SVG 1
```

Ideally, we'd make it a Rust feature that you can opt in. But I'm not sure how to do that properly.

I initially thought something like this in `bind.rs` would work:

```rust
    if cfg!(feature = "svg") {
        cmake_config.define("SUPPORT_FILEFORMAT_SVG", "1");
    }
```

But that only sets the macro for the code generation, and not compilation.
