### ISSUE TITLE
Why??

### ISSUE THREAD

**Issue by taitep** [ewpratten/raylib-ffi#5]
It says you have to build the project, but does not explain how, is it done automatically by cargo? Also, you only give a command to install deps on fedora, and I think not everyone that wants to use this library uses fedora, in fact i am on windows.

**Comment by ewpratten** [comment]
> It says you have to build the project, but does not explain how, is it done automatically by cargo?

Yes, cargo handles it automatically. There's pretty much no reason outside of making a pull request that you'd actually want to manually build this. Just include `raylib-ffi` in your own project's `Cargo.toml`, and cargo will handle everything else.

> you only give a command to install deps on fedora

Well, I use Fedora, and all my friends who use this library also use Fedora, so it made sense at the time of writing.

> I think not everyone that wants to use this library uses fedora

I'd expect that people who want to use Raylib have read [this](https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux) already. But in case they haven't I can add a reference to that page in the README. That way, everyone can have instructions for what to install before building.

> in fact i am on windows

I don't use Windows, so I can't verify that any instructions I might give for it would be correct.

**Comment by Taitep** [comment]
You did add a command written out to install deps on fedora, the linked site has commands that use apt and pacman. You could copy those too if if you did that for fedora.
